# 开发环境配置
app:
  prefix: '/tetap'
  port: 39090
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'

# 数据库配置
db:
  sqlite3:
    database: './databases/app.db'
    entityPrefix: 'tetap_app_'
    logger: 'file'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true
